CREATE TABLE battle_def(
id SERIAL primary key,
year varchar(256),
battle_number varchar(256),
attacker_king varchar(256),
defender_king varchar(256),
attacker_1 varchar,
attacker_2 varchar,
attacker_3 varchar,
attacker_4 varchar,
defender_1 varchar,
defender_2 varchar,
defender_3 varchar,
defender_4 varchar,
attacker_outcome varchar,
battle_type varchar,
major_death varchar,
major_capture varchar,
attacker_Size varchar,
defender_size varchar,
attacker_commander varchar,
defender_commander varchar,
summer varchar,
location varchar,
region varchar,
note varchar
);
